### ISSUE TITLE
Vjoy failed to install Win 11

### ISSUE THREAD

**Issue by BeerHuntor** [njz3/vJoy#11]
Installed the latest release, attempts to install, but fails with popup saying vjoy failed to install.

**Comment by JunpengZhang** [comment]
Hello, has your problem been resolved? I also have a problem here, I wonder if you have ever encountered it? In the first article of this issue

**Comment by salsabeard** [comment]
I ran into this same thing when I tried to upgrade.

**Comment by physius** [comment]
Having the same issue. Vjoy is required for Joystick Gremlin and cannot get Vjoy to install on Windows 11 with latest release.

**Comment by njz3** [comment]
Fixed, see #9

**Comment by tetraflon** [comment]
> Fixed, see #9

Would you add the compiled version in release?

**Comment by njz3** [comment]
Sadly, I can only do a test-signed build (meaning you can only install with a TESTSIGNING enabled windows)
Please see here : https://github.com/shauleiz/vJoy/issues/57#issuecomment-1689885435
