### ISSUE TITLE
Vjoy installation failed

### ISSUE THREAD

**Issue by JunpengZhang** [njz3/vJoy#13]
Hello author, I just compiled the VjoyInstall project and the three driver projects (with digital signature turned off), and all three projects were compiled successfully. Then, I copied the generated files to the "C: Program Files vJoy" directory and ran "vJoyInstall. exe" (I moved the series of files originally installed by the installation package to another location), However, the prompt "cmdUpdate: UPDATEDRIVERFORPLUGANDPLAYDEVICES (hwid=root VID_1234&PID_BEAD&REV_0219, InfPath=C: Program Files vJoy vJoy. inf) failed with error: Unknown Error: e0000247" has been bothering me lately, and I hope to get your help-- A rookie from China

**Comment by JunpengZhang** [comment]
I have found the reason, I pulled the code from the tag. However, in the DriverEntry of the driver. c file in version 2.1.9.1, lines 149 to 178 are duplicated with lines 93-121. The code from lines 149 to 178 should be commented out to run normally!

**Comment by njz3** [comment]
This was a bug from v2.1.9 that has been fixed in v2.2.x.
Now I also fixed a bug in driver.c that was making Windows 11 unhappy when loading the driver.
