### ISSUE TITLE
vJoyInit.reg not found

### ISSUE THREAD

**Issue by Xebozone** [njz3/vJoy#4]
I've just tried to install **vJoySetup-2.2.1-signed.exe**.
At the end of the install, it says that vJoy failed to install.
Looking at the logs, the error I get is 
**_DATETIME_** InitFromRegistry(): File **_DOWNLOADPATH_** vJoyInit.reg not found
Of course, there is no such file in my download path, just the .exe file
[Setup Log 2022-10-19 #004.txt](https://github.com/njz3/vJoy/files/9816325/Setup.Log.2022-10-19.004.txt)

**Comment by micsthepick** [comment]
I'm guessing you are in Windows 11.

for now, it looks like the workaround is to install the older version contained in jshafer817's branch: https://github.com/jshafer817/vJoy/releases/tag/v2.1.9.1
see the following discussion:
https://github.com/shauleiz/vJoy/issues/57#issuecomment-999532470
