### ISSUE TITLE
Joystick Gremlin + Plugin -> vJoy 2.2 doesn't work. 2.1.9 does.

### ISSUE THREAD

**Issue by RedAero** [njz3/vJoy#7]
I don't really know what exactly the problem is, but Joystick Gremlin, via a plugin, can talk just fine with vJoy 2.1.9, but not this fork/version. 

For reproduction, follow the instructions here: https://www.youtube.com/watch?v=zHv14f6s2pQ

It'll work with @jshafer817 version 2.1.9. With this fork, vJoy never detects an input.

**Comment by cyberluke** [comment]
That's correct. This version here is not 2.1.9, but 2.2.x.x

**Comment by cyberluke** [comment]
Two options:
1) look at Joystick Gremlin directory, there are some files DLL files with VJoy name. Now gow to VJoy installation directory, take these DLL files there and copy them to Gremlin directory. This would fix the API.
2) contact Joystick Gremlin and tell them to update VJoy to 2.2.1.1 from here

**Comment by njz3** [comment]
Rejected as issue is actually a dependance in Joystick Gremlin on vJor 2.1.9.x that does not match the new driver version (v2.2.x)
